### PR TITLE
Try to use Fake4

### PR DESCRIPTION
**Pull request by forki**
seems to be broken after second run.

Please don't merge yet

### CODE REVIEW

**Comment by forki** [comment]
mhm I assume the FunScript part is not compatible for now ;-(

**Comment by Krzysztof-Cieslak** [comment]
OK, i don't get something. Why whatever would brake after update to FAKE 4?

**Comment by forki** [comment]
FAKE 4 tries to compile (and cache) the build script. But this one has rather complicated #load directives and executes FunScript. Apparently this is not supported by FAKE 4 atm. `--nocache` works around that issue.

**Comment by Krzysztof-Cieslak** [comment]
OK, Thanks :)

**Pull request merged**
